### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jacob-hegna** [CAPS-Robotics/2013-BuckBeak#1]
Right now the documentation is consistent, but it could still be better.  Using Doxygen could make it more future-proof and could allow other developers on the team to contribute more easily.

**Comment by DweebsUnited** [comment]
Do you know if it is possible to have Doxygen document global functions? I have it working, but it will only document the MyRobit class, which doesn't help all that much..

**Comment by CAPS-Robotics** [comment]
I have a version ready to go, and will push it as soon as I get home.

( Isn't it confusing having me switch between accounts like this? :smile: )

**Comment by DweebsUnited** [comment]
All important comments have been converted to Doxygen format, and a doxyconfig file has been added to the repo. Also, I add the output folder from the config file to a gitignore file.
